version: 2
disabled:
  
  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "preprod"
    schedule:
      interval: "weekly"

  # Maintain dependencies for JS
  - package-ecosystem: "npm"
    directory: "/ui/"
    target-branch: "preprod"
    schedule:
      interval: "weekly"
