---
# Use this configuration to load Proxeus from a local build, rather than DockerHub.
# This file is an override and needs to be used like this:
#
#  docker-compose -f docker-compose.yml -f docker-compose-local.override.yml up

services:
  xes-platform:
    image: !reset null
    build:
      context: .
